#!/bin/sh
set -e
cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x


script/test


# Additional checks which touch the host and thus should run in a sandbox.
cabal sdist
SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}')

cd dist/
if [ -f "$SRC_TGZ" ]; then
    cabal install --force-reinstalls "$SRC_TGZ";
else
    echo "expected '$SRC_TGZ' not found"
    exit 1
fi
